"""create_chats_and_messages

Revision ID: 12729ecf0a8b
Revises: 557bd0014bfb
Create Date: 2026-06-12 11:21:01.412252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12729ecf0a8b'
down_revision: Union[str, None] = '557bd0014bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
